### ISSUE TITLE
Voidbots 

### ISSUE THREAD

**Issue by Cinnamonsroll** [rovelstars/discord-list#406]
Can you allow bot imports from https://voidbots.net (https://api.voidbots.net)

**Comment by sayantan300** [comment]
Ok sure. Our pleasure!

**Comment by sayantan300** [comment]
It will take some time though. I would be looking into docs about it. Will close this once its added. Thanks!

**Comment by sayantan300** [comment]
Uh, can I get your discord tag and ID so I could contact you over discord?

**Comment by sayantan300** [comment]
Looks like youre not on our discord server though.. Please join cause I need to clarify few stuff before heading out for importing this list.

**Comment by sayantan300** [comment]
Anyways, I have added voidbots to import!
Happy coding!
